### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by LydiaMak** [Astro-Sean/autophot#20]
Hi,

I am working on an osx-arm64 which gives me the error that the 3.7 do not exist. Can I use a different python when creating the environment? Will this give me other issues?

Cheers,

Lydia

**Comment by LydiaMak** [comment]
I have created the environment with python 3.8 and then I activated and tried to install but I get 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by GabrielF98** [comment]
I had the same problem - albeit on a mac with an intel chip. 

I got around it by downloading the repo as a zip file. I then extracted this and navigated into the folder. Then I ran this whilst my conda env was activated:

```python setup.py bdist_wheel```

Then when the wheel file is built (it ends up in a folder called dist/) you just run:

```pip install dist/<wheelfile-name>```

**Comment by LydiaMak** [comment]
Hi @GabrielF98 

Thank you for your advice. I get the following error doing this 

 ```
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/lydiamakrygianni/miniconda3/envs/autophot_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lydiamakrygianni/miniconda3/envs/autophot_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/lydiamakrygianni/miniconda3/envs/autophot_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/extension_helpers/_setup_helpers.py", line 67, in get_extensions
          ext_modules.extend(setuppkg.get_extensions())
        File "./astropy/modeling/setup_package.py", line 59, in get_extensions
          from jinja2 import Environment, FileSystemLoader
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
          from jinja2.environment import Environment, Template
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
          from jinja2 import nodes
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
          from jinja2.utils import Markup
        File "/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/jinja2/utils.py", line 642, in <module>
          from markupsafe import Markup, escape, soft_unicode
      ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/private/var/folders/6k/ngfqrzg92fj_bvvmscr6zh080000gn/T/pip-build-env-8j6_1wly/overlay/lib/python3.8/site-packages/markupsafe/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Are you using python 3.8 as well?

**Comment by GabrielF98** [comment]
Hi @LydiaMak I am using python 3.7 in a new conda environment as suggested in the install docs for autophot. 

I'm not exactly sure what is causing your error but you may be missing a package, you should check that the 'markupsafe' python package is installed. This command will check if it is installed and install the package if it is not installed. 

`pip install MarkupSafe`

**Comment by dan-adi** [comment]
Is there a way to install this without conda?

**Comment by tkillestein** [comment]
I managed to get this working on my M2 Mac, using the steps below:

```sh
conda create -n autophot_env
conda activate autophot_env
conda config --env --set subdir osx-64
conda install python=3.7
conda install -c astro-sean autophot

```
although given `autophot` is being rewritten, not sure for how much longer this'll be needed :)
